Tag: Fame
PrefixColor: green
defaultPoints: 50
RankNames:
- None
- Hero
- Fierce Hero
- Mighty Hero
- Deadly Hero
- Terrifying Hero
- Conquering Hero
- Subjugating Hero
- Vanquishing Hero
- Renowned Hero
- Illustrious Hero
- Eminent Hero
- King's Hero
- Emperor's Hero
- Balthazar's Hero
- Legendary Hero
ReqFame:
- 0
- 25
- 75
- 180
- 360
- 600
- 1000
- 1680
- 2800
- 4665
- 7750
- 12960
- 21600
- 36000
- 60000
- 100000
Cash:
  10: give {player} 2 1
  20: give {player} 2 1
  30: give {player} 2 1
