name: Tavern
main: com.suixin.tavern.Tavern
version: ${project.version}
authors:
- 喵♂呜
softdepend:
- Vault
commands:
  rank:
    description: 显示状态
    usage: /rank
  ladder:
    description: 显示前五名玩家
    usage: /ladder
  cash:
    description: 兑换物品
    usage: /cash
  tnopen:
    description: 打开GUI
    usage: /tnopen
  tnbet:
    description: 下注
    usage: /tnbet
permissions:
  tavern.rank:
    description: Allows you to see rank
  tavern.ladder:
    description: Allows you to see the ladder
  tavern.fame:
    description: Allow you to use fame