name: TownyLeader
main: com.suixin.townyleader.TownyLeader
version: ${project.version}
authors:
- suixin
commands:
  townyleader:
    description:
    usage: /townyleader
permissions:
  townyleader.tn:
    description: Allows you to use townyleader