name: Tavern
main: com.suixin.tavern.Tavern
version: ${project.version}
authors:
- suixin
softdepend:
- Vault
commands:
  tn:
    description:
    usage: /tn
permissions:
  tavern.rank:
    description: Allows you to see rank
  tavern.ladder:
    description: Allows you to see the ladder
  tavern.fame:
    description: Allow you to use fame