name: TownyLeader
main: com.suixin.tavern.TownyLeader
version: ${project.version}
authors:
- suixin
commands:
  tn:
    description:
    usage: /townyleader
permissions:
  townyleader.tn:
    description: Allows you to use tn