name: Tavern
main: com.suixin.tavern.Tavern
version: ${project.version}
authors:
- suixin
softdepend:
- Vault
- PlayerPoints
- TitleManager
commands:
  tn:
    description:
    usage: /tn
permissions:
  tavern.tn:
    description: Allows you to use tn